name: Release All Binaries

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build and Upload All Binaries
    runs-on: ubuntu-22.04
    container: swift:6.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and package manager
        working-directory: ./manager
        run: |
          swift build --static-swift-stdlib -c release
          APP_NAME="manager"
          ARCH=$(uname -m)
          OS="ubuntu22.04"
          OUTPUT="${APP_NAME}-${OS}-${ARCH}-static.tar.gz"
          tar -czvf $OUTPUT -C .build/release App
          mv $OUTPUT ../

      - name: Build and package wsm-ctl
        working-directory: ./wsm-ctl
        run: |
          swift build --static-swift-stdlib -c release
          APP_NAME="wsm-ctl"
          ARCH=$(uname -m)
          OS="ubuntu22.04"
          OUTPUT="${APP_NAME}-${OS}-${ARCH}-static.tar.gz"
          tar -czvf $OUTPUT -C .build/release wsm
          mv $OUTPUT ../

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manager-ubuntu22.04-*-static.tar.gz
            wsm-ctl-ubuntu22.04-*-static.tar.gz