name: Release All Binaries

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build and Upload All Binaries
    runs-on: ubuntu-24.04
    container: swift:6.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Swift dependencies - Manager
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.swiftpm
            manager/.build
          key: ${{ runner.os }}-whooshing.manager-${{ hashFiles('manager/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-whooshing.manager-

      - name: Cache Swift dependencies - Wsm
        uses: actions/cache@v4.2.0
        with:
          path: |
            wsm-ctl/.build
          key: ${{ runner.os }}-wsm-ctl-${{ hashFiles('wsm-ctl/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-wsm-ctl-

      - name: Build and package manager
        working-directory: ./manager
        run: bash ./release.sh

      - name: Build and package wsm-ctl
        working-directory: ./wsm-ctl
        run: bash ./release.sh

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CLWANG_RELEASE_ACCESS }}
        with:
          files: |
            *.tar.gz